### ISSUE TITLE
Exception when path contains unicode character

### ISSUE THREAD

**Issue by ftiff** [timsutton/mcxToProfile#17]
Hi Tim, 
Thanks for your work, it's an awesome tool!

When the path contains a unicode character ("François") in my case, the script refuses to write the file:
```
[fti@Gramont Desktop]$ cd François\ CP/
[fti@Gramont François CP]$ ./mcx2profile.py --plist com.apple.security.firewall.plist --identifier com.apple.security.firewallTraceback (most recent call last):
  File "./mcx2profile.py", line 539, in <module>
    main()
  File "./mcx2profile.py", line 534, in main
    newPayload.finalizeAndSave(output_file)
  File "./mcx2profile.py", line 138, in finalizeAndSave
    writePlist(self.data, output_path)
  File "./mcx2profile.py", line 256, in writePlist
    "Failed to write plist data to %s" % filepath)
__main__.NSPropertyListWriteException: Failed to write plist data to /Users/fti/Desktop/François CP/com.apple.security.firewall.mobileconfig
[fti@Gramont François CP]$
```

**Comment by alifkifi** [comment]
ali
